FROM node:21.5-alpine as build-stage
#Create a new user
#RUN addgroup node && adduser -S -G node node

WORKDIR /app
RUN chown -R node:node /app
COPY package*.json ./
#Set current user
USER node

# Updating packages and fixing vulnerabilities
RUN npm update 
RUN npm cache clean --force
RUN npm install

COPY --chown=node:node . .

# DEVELOPMENT STAGE
FROM build-stage as dev-stage
RUN npm install nodemon
EXPOSE 3000
CMD ["npm", "run", "start.dev"]

# PRODUCTION STAGE
FROM build-stage as prod-stage
EXPOSE 3000
CMD ["node", "main.js"]